import time
import sys
import os
import logging
from sqlalchemy import create_engine, text

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("MatrixVerifier")

def get_engine(db_url):
    retries = 120 # Wait up to 4 minutes for slow DBs (Oracle/MSSQL)
    while retries > 0:
        try:
            engine = create_engine(db_url)
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            return engine
        except Exception as e:
            logger.info(f"Waiting for {db_url}... ({e})")
            time.sleep(2)
            retries -= 1
    raise Exception(f"Could not connect to {db_url}")

def seed_postgres(url):
    logger.info("Seeding Postgres...")
    engine = get_engine(url)
    with engine.connect() as conn:
        conn.execute(text("CREATE TABLE IF NOT EXISTS inventory (id SERIAL PRIMARY KEY, item TEXT, count INTEGER)"))
        conn.execute(text("INSERT INTO inventory (item, count) VALUES ('Apple', 10), ('Banana', 20)"))
        conn.commit()

def seed_mysql(url):
    logger.info("Seeding MySQL...")
    engine = get_engine(url)
    with engine.connect() as conn:
        conn.execute(text("CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255), active BOOLEAN)"))
        conn.execute(text("INSERT INTO users (username, active) VALUES ('alice', true), ('bob', false)"))
        conn.commit()

def seed_mssql(url):
    logger.info("Seeding MSSQL...")
    engine = get_engine(url)
    with engine.connect() as conn:
        conn.execute(text("IF OBJECT_ID('dbo.products', 'U') IS NULL CREATE TABLE products (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(50), price DECIMAL(10,2))"))
        # Check if empty to avoid dups on re-run
        result = conn.execute(text("SELECT COUNT(*) FROM products")).scalar()
        if result == 0:
            conn.execute(text("INSERT INTO products (name, price) VALUES ('Widget', 9.99), ('Gadget', 19.99)"))
            conn.commit()

def seed_oracle(url):
    logger.info("Seeding Oracle...")
    # Oracle requires auto-increment trigger or IDENTITY (12c+)
    # We use IDENTITY generated always.
    engine = get_engine(url)
    with engine.connect() as conn:
        try:
            # Drop if exists (manual drop because IF EXISTS is 23c+)
            try:
                conn.execute(text("DROP TABLE \"employees\""))
            except Exception:
                pass
                
            conn.execute(text("""
                CREATE TABLE "employees" (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(100),
                    role VARCHAR2(50)
                )
            """))
            conn.execute(text("INSERT INTO \"employees\" (name, role) VALUES ('Charlie', 'Dev')"))
            conn.execute(text("INSERT INTO \"employees\" (name, role) VALUES ('Dave', 'Ops')"))
            conn.commit()
        except Exception as e:
            logger.error(f"Oracle seed failed: {e}")
            raise

def verify_target(url, table, expected_count):
    logger.info(f"Verifying {url} table {table}...")
    engine = get_engine(url)
    with engine.connect() as conn:
        result = conn.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar()
        if result != expected_count:
            logger.error(f"Verification FAILED for {table}: expected {expected_count}, got {result}")
            return False
        logger.info(f"Verification PASSED for {table}")
        return True

if __name__ == "__main__":
    action = sys.argv[1]
    
    if action == "seed":
        seed_postgres(os.environ["SOURCE_POSTGRES_URL"])
        seed_mysql(os.environ["SOURCE_MYSQL_URL"])
        seed_mssql(os.environ["SOURCE_MSSQL_URL"])
        seed_oracle(os.environ["SOURCE_ORACLE_URL"])
    elif action == "verify":
        success = True
        success &= verify_target(os.environ["TARGET_POSTGRES_URL"], "inventory", 2)
        success &= verify_target(os.environ["TARGET_MYSQL_URL"], "users", 2)
        success &= verify_target(os.environ["TARGET_MSSQL_URL"], "products", 2)
        # Verify MSSQL -> PG/MySQL (products table)
        success &= verify_target(os.environ["TARGET_POSTGRES_URL"], "products", 2)
        success &= verify_target(os.environ["TARGET_MYSQL_URL"], "products", 2)
        # Verify PG -> MSSQL (inventory table)
        success &= verify_target(os.environ["TARGET_MSSQL_URL"], "inventory", 2)
        # Verify Oracle -> PG (employees table)
        success &= verify_target(os.environ["TARGET_POSTGRES_URL"], "employees", 2)
        
        if not success:
            sys.exit(1)
